services:
    app:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        image: monata-laravel
        container_name: monata-laravel
        volumes:
            - .:/var/www
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "8080:8000"
        depends_on:
            - mysql
        networks:
            - monata-network

    mysql:
        image: mysql:8
        container_name: monata-mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - monata-network

    nginx:
        image: nginx:alpine
        container_name: monata-nginx
        ports:
            - "8800:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - monata-network

volumes:
    mysql_data:

networks:
    monata-network:
        driver: bridge
